name: Doppler Secrets

on: workflow_dispatch

jobs:
  secrets-fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ryan-blunden/secrets-fetch-action@7b5d5e29eb82a47883ae088ec5f9ffbd2ddba66b
      id: doppler
      with:
        doppler-token: ${{ secrets.DOPPLER_TOKEN }}
        inject-env-vars: true
    - run: echo "DOPPLER_PROJECT is ${{ steps.doppler.outputs.DOPPLER_PROJECT }}"
    - run: printenv
    - run: sh ./test-script.sh

