name: Doppler Secrets

on: workflow_dispatch

jobs:
  secrets-fetch-service-token:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dopplerhq/secrets-fetch-action@c7d9f5c2b3277ef62ba81fb2eb5984581e062ee1
      id: doppler
      with:
        doppler-token: ${{ secrets.DOPPLER_TOKEN }}
        inject-env-vars: true
    - run: echo "DOPPLER_PROJECT is ${{ steps.doppler.outputs.DOPPLER_PROJECT }}"
    - run: printenv
    - run: sh ./test-script.sh

  # Fails as doppler-project and doppler-config are not supplied
  secrets-fetch-personal-token-fail:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dopplerhq/secrets-fetch-action@c7d9f5c2b3277ef62ba81fb2eb5984581e062ee1
      id: doppler
      with:
        doppler-token: ${{ secrets.DOPPLER_PERSONAL_TOKEN }}
        inject-env-vars: true
    - run: echo "DOPPLER_PROJECT is ${{ steps.doppler.outputs.DOPPLER_PROJECT }}"
    - run: printenv
    - run: sh ./test-script.sh
    
# Succeeds as doppler-project and doppler-config are defined
  secrets-fetch-personal-token-success:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: dopplerhq/secrets-fetch-action@c7d9f5c2b3277ef62ba81fb2eb5984581e062ee1
      id: doppler
      with:
        doppler-token: ${{ secrets.DOPPLER_PERSONAL_TOKEN }}
        doppler-project: auth-api
        doppler-config: prd
        inject-env-vars: true
    - run: echo "DOPPLER_PROJECT is ${{ steps.doppler.outputs.DOPPLER_PROJECT }}"
    - run: printenv
    - run: sh ./test-script.sh
    

  



  

